### ISSUE TITLE
Duke perfect tracker remains in fail state even after he is killed

### ISSUE THREAD

**Issue by Laureeeeeeeeeeeeeeen** [DominickCobb-rs/DT2-Boss-Failure#2]
Not intermittent, this happens every time.  
Upon making a mistake the perfect tracker switches to failed as normal. But when you kill Duke and reset for another kill it doesn't go back to green, making it useless for any subsequent kills on the trip.
The tracker doesn't reset to the green check until you leave the boss room.

**Comment by DominickCobb-rs** [comment]
Hey! I'll take a look at this after I get my rancor (soon TM). I'll add some other conditions for reset.

If you're confident with Java, my current ideas for fixing this are resetting on client loading and the region not being Duke region (tp out/walkout), chat message for death, and chat message for duke kc increasing.

**Comment by DominickCobb-rs** [comment]
Resolved with d213eb20524d299eec2777ded6fae6020e734c5f
